### ISSUE TITLE
upload to maven central

### ISSUE THREAD

**Issue by r0bnewt0n** [FrankHossfeld/gwt-json#4]
Hi, it would be useful to be able to use this project directly from maven central.  Some of the GWT 3 ported projects such as gwt-timer have done this already.   Any chance you could upload to maven central?

**Comment by FrankHossfeld** [comment]
Hi, this is in progress, but requires that all other modules also are ready for maven central.

**Comment by r0bnewt0n** [comment]
The pom depends on org.gwtproject.core:gwt-core from the Sonatype repo -- that's what you are refering to?    Ah, now I see the references to `org.gwtproject.core.client.JavaScriptObject` and `org.gwtproject.core.client.JsonUtils` that are in gwt-core.  Makes sense now.  Thanks
